project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - full_keyword_network.qmd
  - research_cluster_two.qmd
  - about.qmd

website:
  title: "The SMU-affiliated Research Corpus"
  navbar:
    right:
      - href: about.qmd
        text: About
    left:
      - href: index.qmd
        text: Start Here
      - href: full_keyword_network.qmd
        text: The SMU-affililated Corpus
      - href: research_cluster_two.qmd
        text: Research Cluster Two

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

bibliography: references.bib

execute:
  echo: false
  warning: false
  message: false


