project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - full_keyword_network.qmd
  - about.qmd

website:
  title: "The SMU-affiliated Research Corpus"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: full_keyword_network.qmd
        text: Keyword Network

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

bibliography: references.bib

execute:
  echo: false
  warning: false
  message: false


